version: '3'
services:
  web:
#    build: .
    build:
      context: .
      dockerfile: Dockerfile.dev # look for Dockerfile.dev instead of
      # the conventional Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
